name: Build

on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 0 ? * FRI

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache file
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            %APPDATA%\npm-cache
            %LOCALAPPDATA%\electron\Cache
            %LOCALAPPDATA%\electron-builder\Cache
          key: ${{ runner.os }}-build-caches-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update package.json
        run: ncu -u

      - name: Install Dependencies
        run: npm install --force

      - name: Build src code
        run: npm run build:src

      - name: Build Package Setup x64
        run: npm run pack:win:setup:x64

      - name: Upload Artifact Setup x64
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-x64-Setup
          path: build/* x64 Setup.exe

      - name: Build Package Setup x86
        run: npm run pack:win:setup:x86

      - name: Upload Artifact Setup x86
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-x86-Setup
          path: build/* x86 Setup.exe

      - name: Build Package Setup arm64
        run: npm run pack:win:setup:arm64

      - name: Upload Artifact Setup arm64
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-arm64-Setup
          path: build/* arm64 Setup.exe

      - name: Build Package Setup x86_64
        run: npm run pack:win:setup:x86_64

      - name: Upload Artifact Setup x86_64
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-x86_64-Setup
          path: build/*x86_64 Setup.exe

      - name: Build Package 7z x64
        run: npm run pack:win:7z:x64

      - name: Upload Artifact 7z x64
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-win_x64-green
          path: build/*win_x64 green.7z

      - name: Build Package 7z x86
        run: npm run pack:win:7z:x86

      - name: Upload Artifact 7z x86
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-win_x86-green
          path: build/*win_x86 green.7z

      - name: Build Package 7z arm64
        run: npm run pack:win:7z:arm64

      - name: Upload Artifact 7z arm64
        uses: actions/upload-artifact@v2
        with:
          name: lx-music-desktop-win_arm64-green
          path: build/*win_arm64 green.7z
